AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Genera il repository maven e include gli stack di generazione dei CodeBuild project per 
  effettuare il build di librerie, microservizi e webapp.

Parameters:
  PnCiCdTemplatesBucketName:
    Type: String
    Description: Bucket name where pipeline copied the current version of CI templates
  CodeArtifactDomainName:
    Type: String
    Default: test-cicd-codeartifact-domain
  CodeArtifactRepositoryName:
    Type: String
    Default: test-cicd-codeartifact-repo

  AllowedDeployAccount1:
    Type: Number
    Description: Account number allowed to read the artifacts

Resources:
  CodeArtifactStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/infra/code-artifact.yaml"
      Parameters:
        CodeArtifactDomainName: !Ref "CodeArtifactDomainName"
        CodeArtifactRepositoryName: !Ref "CodeArtifactRepositoryName"
      TimeoutInMinutes: 5

  CiArtifactBucket:
    Type: AWS::S3::Bucket
    #DeletionPolicy: Retain
    #UpdateReplacePolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CiEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: "TestCiEventBus"

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CiArtifactBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:Get*
              - s3:List*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${CiArtifactBucket}
              - !Sub arn:aws:s3:::${CiArtifactBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AllowedDeployAccount1}:root
  
  # Progetti WebApp
  PnLandingWebapp:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/webapp-standard-codebuild.yaml"
      Parameters:
        GitHubProjectName: "test-cicd"
        PackageName: "test-webapp"
        BaseDir: "packages/test-webapp"
        CodeArtifactDomainName: !Ref "CodeArtifactDomainName"
        CodeArtifactRepositoryName: !Ref "CodeArtifactRepositoryName"
        CiArtifactBucket: !Ref "CiArtifactBucket"
      TimeoutInMinutes: 5
  # Web sonar pipeline
  # TODO

  # Web cypress pipeline
  # TODO

  # Progetti template CFN
  # TODO PnInfra
  PnCiCd:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${PnCiCdTemplatesBucketName}/ci/builders/not-compiled-repo-codebuild.yaml"
      Parameters:
        GitHubProjectName: "test-cicd"
        GitHubDefaultBranch: "develop"
      TimeoutInMinutes: 5

Outputs:
  CiArtifactBucket:
    Value: !Ref "CiArtifactBucket"
